model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    # ckpt_path: last.ckpt # Uncomment to resume training from checkpoint
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: image
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: concat
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 8
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        - 4
        - 2
        num_res_blocks: 1
        channel_mult:
        - 1
        - 1
        - 2
        num_head_channels: 32
        transformer_depth: 1
        use_spatial_transformer: false
    first_stage_config:
      target: ldm.models.vqgan.VQModel
      params:
        num_classes: 1
        # ckpt_path: stage2.ckpt # Path to pretrained VQ-GAN - train VQ-GAN first or remove to train from scratch
        stage: 2
        embed_dim: 4
        n_embed: 8192
        ddconfig:
          double_z: False
          z_channels: 4
          resolution: 160
          in_channels: 1
          out_ch: 1
          ch: 64
          num_groups: 32
          ch_mult:
          - 1
          - 1
          - 2
          num_res_blocks: 1
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 12
    train:
      target: ldm.data.ulf.ULFtoHFTrain
      params:
        ulf_path: /content/dataset/ULF-v1/ULF-v1Tr
        hf_path: /content/dataset/HF/HFTr
    validation:
      target: ldm.data.ulf.ULFtoHFVal
      params:
        ulf_path: /content/dataset/ULF-v1/ULF-v1Val
        hf_path: /content/dataset/HF/HFVal
    test:
      target: ldm.data.ulf.ULFtoHFTest
      params:
        ulf_path: /content/dataset/ULF-v1/ULF-v1Val
        hf_path: /content/dataset/HF/HFVal


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    max_epochs: 200
    check_val_every_n_epoch: 20
    benchmark: True
